### ISSUE TITLE
Incorrect filtering output file names

### ISSUE THREAD

**Issue by w-koder** [dtsoucas/GiniClust2#2]
Filtering script produces 2 CSV files "..._gene.expression.matrix.normCounts.filtered.csv" and "..._gene.expression.matrix.RawCounts.filtered.csv". But actually, normCounts.filter variable is in the second file and RawCounts.filter variable is in the first one. Just check lines 16 and 17 in GiniClust2_filtering_RawCounts.R

**Comment by dtsoucas** [comment]
Thank you for catching this.  I have swapped these variable names— note that this will not affect the final clustering as these files are not used in the further code.

**Comment by w-koder** [comment]
Thank you for the fast answer. Hope it helps to improve the project)
